// Mocks generated by Mockito 5.4.4
// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i2;

import 'package:connectivity_plus/connectivity_plus.dart' as _i5;
import 'package:hyprspace_flutter/core/network/vpn_native_bridge.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

class MockVpnNativeBridge extends _i1.Mock implements _i3.VpnNativeBridge {
  MockVpnNativeBridge() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void load() => super.noSuchMethod(
        Invocation.method(#load, []),
        returnValueForMissingStub: null,
      );

  @override
  int init() => (super.noSuchMethod(
        Invocation.method(#init, []),
        returnValue: 0,
      ) as int);

  @override
  int startNode(String? privateKey, int? listenPort) =>
      (super.noSuchMethod(
        Invocation.method(#startNode, [privateKey, listenPort]),
        returnValue: 0,
      ) as int);

  @override
  void stopNode() => super.noSuchMethod(
        Invocation.method(#stopNode, []),
        returnValueForMissingStub: null,
      );

  @override
  int addPeer(String? peerId, String? peerIp) =>
      (super.noSuchMethod(
        Invocation.method(#addPeer, [peerId, peerIp]),
        returnValue: 0,
      ) as int);

  @override
  int removePeer(String? peerId) => (super.noSuchMethod(
        Invocation.method(#removePeer, [peerId]),
        returnValue: 0,
      ) as int);

  @override
  int sendPacket(_i2.Uint8List? data) => (super.noSuchMethod(
        Invocation.method(#sendPacket, [data]),
        returnValue: 0,
      ) as int);

  @override
  int receivePacket(_i2.Uint8List? buffer) => (super.noSuchMethod(
        Invocation.method(#receivePacket, [buffer]),
        returnValue: 0,
      ) as int);

  @override
  ({int bytesSent, int bytesReceived}) getStatsBytes() =>
      (super.noSuchMethod(
        Invocation.method(#getStatsBytes, []),
        returnValue: (bytesSent: 0, bytesReceived: 0),
      ) as ({int bytesSent, int bytesReceived}));

  @override
  int createTun(String? name, String? address, int? mtu) =>
      (super.noSuchMethod(
        Invocation.method(#createTun, [name, address, mtu]),
        returnValue: 0,
      ) as int);
}

class MockConnectivity extends _i1.Mock implements _i5.Connectivity {
  MockConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.ConnectivityResult> get onConnectivityChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onConnectivityChanged),
        returnValue: const Stream.empty(),
      ) as _i4.Stream<_i5.ConnectivityResult>);

  @override
  _i4.Future<_i5.ConnectivityResult> checkConnectivity() =>
      (super.noSuchMethod(
        Invocation.method(#checkConnectivity, []),
        returnValue: Future.value(_i5.ConnectivityResult.none),
      ) as _i4.Future<_i5.ConnectivityResult>);
}
